name: Code Quality
on:
  workflow_call:
    secrets:
      SEMGREP_APP_TOKEN_PUBLIC:
        required: true
        description: "required for analysis"
jobs:
  validation-job:
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.private == false }}
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v4.0.0
      - name: code quality analysis
        run: semgrep ci --pro-intrafile &> /dev/null
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN_PUBLIC }}
